{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "library(\"quantmod\")\n",
    "library(\"tseries\")\n",
    "## Set the random seed to 123\n",
    "\n",
    "set.seed(123)\n",
    "## SIMULATED DATA\n",
    "## Create a simulated random walk\n",
    "z <- rep(0, 1000)\n",
    "for (i in 2:1000) z[i] <- z[i-1] + rnorm(1)\n",
    "## Create two non-stationary series based on the\n",
    "## simulated random walk\n",
    "p <- q <- rep(0, 1000)\n",
    "p <- 0.3*z + rnorm(1000)\n",
    "q <- 0.6*z + rnorm(1000)\n",
    "## Perform a linear regression against the two\n",
    "## simulated series in order to assess the hedge ratio\n",
    "comb <- lm(p~q)\n",
    "## FINANCIAL DATA - EWA/EWC\n",
    "## Obtain EWA and EWC for dates corresponding to Chan (2013)\n",
    "getSymbols(\"EWA\", from=\"2006-04-26\", to=\"2012-04-09\")\n",
    "getSymbols(\"EWC\", from=\"2006-04-26\", to=\"2012-04-09\")\n",
    "## Utilise the backwards-adjusted closing prices\n",
    "ewaAdj = unclass(EWA$EWA.Adjusted)\n",
    "ewcAdj = unclass(EWC$EWC.Adjusted)\n",
    "## Plot the ETF backward-adjusted closing prices\n",
    "plot(ewaAdj, type=\"l\", xlim=c(0, 1500), ylim=c(5.0, 35.0),\n",
    "xlab=\"April 26th 2006 to April 9th 2012\",\n",
    "ylab=\"ETF Backward-Adjusted Price in USD\", col=\"blue\")\n",
    "par(new=T)\n",
    "plot(ewcAdj, type=\"l\", xlim=c(0, 1500), ylim=c(5.0, 35.0),\n",
    "axes=F, xlab=\"\", ylab=\"\", col=\"red\")\n",
    "par(new=F)\n",
    "## Plot a scatter graph of the ETF adjusted prices\n",
    "plot(ewaAdj, ewcAdj, xlab=\"EWA Backward-Adjusted Prices\",\n",
    "ylab=\"EWC Backward-Adjusted Prices\")\n",
    "## Carry out linear regressions twice, swapping the dependent\n",
    "## and independent variables each time, with zero drift\n",
    "comb1 = lm(ewcAdj~ewaAdj)\n",
    "comb2 = lm(ewaAdj~ewcAdj)\n",
    "\n",
    "## Plot the residuals of the first linear combination\n",
    "plot(comb1$residuals, type=\"l\",\n",
    "xlab=\"April 26th 2006 to April 9th 2012\",\n",
    "ylab=\"Residuals of EWA and EWC regression\")\n",
    "## Now we perform the ADF test on the residuals,\n",
    "## or \"spread\" of each model, using a single lag order\n",
    "adf.test(comb1$residuals, k=1)\n",
    "adf.test(comb2$residuals, k=1)\n",
    "## FINANCIAL DATA - RDS-A/RDS-B\n",
    "## Obtain RDS equities prices for a recent ten year period\n",
    "getSymbols(\"RDS-A\", from=\"2006-01-01\", to=\"2015-12-31\")\n",
    "getSymbols(\"RDS-B\", from=\"2006-01-01\", to=\"2015-12-31\")\n",
    "## Avoid the hyphen in the name of each variable\n",
    "RDSA <- get(\"RDS-A\")\n",
    "RDSB <- get(\"RDS-B\")\n",
    "## Utilise the backwards-adjusted closing prices\n",
    "rdsaAdj = unclass(RDSA$\"RDS-A.Adjusted\")\n",
    "rdsbAdj = unclass(RDSB$\"RDS-B.Adjusted\")\n",
    "## Plot the ETF backward-adjusted closing prices\n",
    "plot(rdsaAdj, type=\"l\", xlim=c(0, 2517), ylim=c(25.0, 80.0),\n",
    "xlab=\"January 1st 2006 to December 31st 2015\",\n",
    "ylab=\"RDS-A and RDS-B Backward-Adjusted Closing Price in GBP\", col=\"blue\")\n",
    "par(new=T)\n",
    "plot(rdsbAdj, type=\"l\", xlim=c(0, 2517), ylim=c(25.0, 80.0),\n",
    "axes=F, xlab=\"\", ylab=\"\", col=\"red\")\n",
    "par(new=F)\n",
    "## Plot a scatter graph of the\n",
    "## Royal Dutch Shell adjusted prices\n",
    "plot(rdsaAdj, rdsbAdj, xlab=\"RDS-A Backward-Adjusted Prices\",\n",
    "ylab=\"RDS-B Backward-Adjusted Prices\")\n",
    "## Carry out linear regressions twice, swapping the dependent\n",
    "## and independent variables each time, with zero drift\n",
    "comb1 = lm(rdsaAdj~rdsbAdj)\n",
    "comb2 = lm(rdsbAdj~rdsaAdj)\n",
    "## Plot the residuals of the first linear combination\n",
    "\n",
    "plot(comb1$residuals, type=\"l\",\n",
    "xlab=\"January 1st 2006 to December 31st 2015\",\n",
    "ylab=\"Residuals of RDS-A and RDS-B regression\")\n",
    "## Now we perform the ADF test on the residuals,\n",
    "## or \"spread\" of each model, using a single lag order\n",
    "adf.test(comb1$residuals, k=1)\n",
    "adf.test(comb2$residuals, k=1)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
